# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup

title:            CARNIVAL
tagline:          Phosphorylation Networks for Mass Spectrometry
description:      "Method to model signaling networks based on untargeted phosphoproteomics data"
#url:              https://github.com/saezlab/CARNIVAL
baseurl:          /CARNIVAL/
toollogo:         /CARNIVAL/public/logo.jpg

author:
  name:           'Enio Gjerga'

paginate:         5

# Custom vars
version:          2

github:
  repo:           https://github.com/saezlab/CARNIVAL
